### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by MartinThoma** [vwt-digital/sec-helpers#21]
What do you think about a CLI for sec-helpers? I could create one with [`click`](https://pypi.org/project/click) if you're interested :-)

**Comment by MaxvanderWeide** [comment]
Hey @MartinThoma,
Thanks for the offer! For us, a CLI does not seem necessary. We use sec-helpers in automated builds with [cloudbuilder-dast](https://github.com/vwt-digital/cloudbuilder-dast/blob/develop/dast.py). The idea is awesome though, so we would suggest you go through with the plan and create a CLI in a seperate repository that we can then reference in the README.

**Comment by dvanrhenen** [comment]
Closed due to inactivity
